### ISSUE TITLE
Value error in inference with heat model and PCA

### ISSUE THREAD

**Issue by castellinilinguini** [Systems-Theory-in-Systems-Biology/EPI#68]
**Describe the bug**
When trying to use PCA with the heat model, eulerpi crashes.

**To Reproduce**
```python

from eulerpi.examples.heat import HeatArtificial
from eulerpi.core.data_transformation_types import DataTransformationType
from eulerpi.core.inference import inference
from eulerpi.core.inference import InferenceType
import numpy as np

# create model
heat_model = HeatArtificial()
heat_num_params = 1000

# generate artificial data
heat_params = heat_model.generate_artificial_params(heat_num_params)
heat_data = heat_model.generate_artificial_data(heat_params)

# run EPI with one trivial slice
heat_num_grid_points = 1000
heat_slices = [np.array([0])]

# dense grid inference
heat_dense_grid_overall_params, heat_dense_grid_sim_results, heat_dense_grid_density_evals, heat_dense_grid_results_manager = inference(
    model = heat_model,
    data = heat_data,
    inference_type = InferenceType.DENSE_GRID,
    num_grid_points = heat_num_grid_points,
    slices = heat_slices,
    data_transformation = DataTransformationType.PCA,
    run_name = "dense_grid_run",
)

```
**Expected behavior**
Eulerpi runs dense grid inference with transformation type PCA.

**Observed behavior**
Eulerpi crashes with message
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/benjamin/Uni/Masterarbeit/EPI/eulerpi/core/dense_grid.py", line 106, in evaluate_on_grid_chunk
    density, param_sim_res_density = evaluate_density(
  File "/home/benjamin/Uni/Masterarbeit/EPI/eulerpi/core/transformations.py", line 89, in evaluate_density
    evaluation_results = np.concatenate(
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 2 has 2 dimension(s)
```

**Additional context**
OS Ubuntu 22.04 LTS

**Comment by kaiserls** [comment]
The problem lies in this line:
`transformed_sim_res = data_transformation.transform(sim_res)`
It is caused by the reshaping in the transform function of the PCA:
`    def transform(self, data: jnp.ndarray) -> jnp.ndarray:
        """Transform the given data using the PCA.

        Args:
            data (jnp.ndarray): The data to be transformed.

        Returns:
            jnp.ndarray: The data projected onto and expressed in the basis of the principal components.
        """
        return self.pca.transform(data.reshape(-1, data.shape[-1])).reshape(
            -1, self.pca.n_components_
        )`
I am not sure how to fix this in a nice way, if we want to keep the option open to have vector valued evaluations.
